// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class ActivityConfigKaifuJinSai implements Externalizable, Message<ActivityConfigKaifuJinSai>
{

    public static Schema<ActivityConfigKaifuJinSai> getSchema()
    {
        return SCHEMA;
    }

    public static ActivityConfigKaifuJinSai getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ActivityConfigKaifuJinSai DEFAULT_INSTANCE = new ActivityConfigKaifuJinSai();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer type;
    Integer level;
    List<Award> award;

    public ActivityConfigKaifuJinSai()
    {

    }

    public ActivityConfigKaifuJinSai(
        Integer type,
        Integer level
    )
    {
        this.type = type;
        this.level = level;
    }

    // getters and setters

    // type

    public Integer getType()
    {
        return type;
    }


    public void setType(Integer type)
    {
        this.type = type;
    }

    // level

    public Integer getLevel()
    {
        return level;
    }


    public void setLevel(Integer level)
    {
        this.level = level;
    }

    // award

    public List<Award> getAwardList()
    {
        return award;
    }


    public void setAwardList(List<Award> award)
    {
        this.award = award;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<ActivityConfigKaifuJinSai> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<ActivityConfigKaifuJinSai> SCHEMA = new Schema<ActivityConfigKaifuJinSai>()
    {
        // schema methods

        public ActivityConfigKaifuJinSai newMessage()
        {
            return new ActivityConfigKaifuJinSai();
        }

        public Class<ActivityConfigKaifuJinSai> typeClass()
        {
            return ActivityConfigKaifuJinSai.class;
        }

        public String messageName()
        {
            return ActivityConfigKaifuJinSai.class.getSimpleName();
        }

        public String messageFullName()
        {
            return ActivityConfigKaifuJinSai.class.getName();
        }

        public boolean isInitialized(ActivityConfigKaifuJinSai message)
        {
            return 
                message.type != null 
                && message.level != null;
        }

        public void mergeFrom(Input input, ActivityConfigKaifuJinSai message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.type = input.readInt32();
                        break;
                    case 2:
                        message.level = input.readInt32();
                        break;
                    case 3:
                        if(message.award == null)
                            message.award = new ArrayList<Award>();
                        message.award.add(input.mergeObject(null, Award.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, ActivityConfigKaifuJinSai message) throws IOException
        {
            if(message.type == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.type, false);

            if(message.level == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.level, false);

            if(message.award != null)
            {
                for(Award award : message.award)
                {
                    if(award != null)
                        output.writeObject(3, award, Award.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "type";
                case 2: return "level";
                case 3: return "award";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("type", 1);
            fieldMap.put("level", 2);
            fieldMap.put("award", 3);
        }
    };
    
}
