// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class ActivityConfigOneFuLi implements Externalizable, Message<ActivityConfigOneFuLi>
{

    public static Schema<ActivityConfigOneFuLi> getSchema()
    {
        return SCHEMA;
    }

    public static ActivityConfigOneFuLi getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ActivityConfigOneFuLi DEFAULT_INSTANCE = new ActivityConfigOneFuLi();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer level;
    Integer vipLevel;
    List<Award> award;

    public ActivityConfigOneFuLi()
    {

    }

    public ActivityConfigOneFuLi(
        Integer level,
        Integer vipLevel
    )
    {
        this.level = level;
        this.vipLevel = vipLevel;
    }

    // getters and setters

    // level

    public Integer getLevel()
    {
        return level;
    }


    public void setLevel(Integer level)
    {
        this.level = level;
    }

    // vipLevel

    public Integer getVipLevel()
    {
        return vipLevel;
    }


    public void setVipLevel(Integer vipLevel)
    {
        this.vipLevel = vipLevel;
    }

    // award

    public List<Award> getAwardList()
    {
        return award;
    }


    public void setAwardList(List<Award> award)
    {
        this.award = award;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<ActivityConfigOneFuLi> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<ActivityConfigOneFuLi> SCHEMA = new Schema<ActivityConfigOneFuLi>()
    {
        // schema methods

        public ActivityConfigOneFuLi newMessage()
        {
            return new ActivityConfigOneFuLi();
        }

        public Class<ActivityConfigOneFuLi> typeClass()
        {
            return ActivityConfigOneFuLi.class;
        }

        public String messageName()
        {
            return ActivityConfigOneFuLi.class.getSimpleName();
        }

        public String messageFullName()
        {
            return ActivityConfigOneFuLi.class.getName();
        }

        public boolean isInitialized(ActivityConfigOneFuLi message)
        {
            return 
                message.level != null 
                && message.vipLevel != null;
        }

        public void mergeFrom(Input input, ActivityConfigOneFuLi message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.level = input.readInt32();
                        break;
                    case 2:
                        message.vipLevel = input.readInt32();
                        break;
                    case 3:
                        if(message.award == null)
                            message.award = new ArrayList<Award>();
                        message.award.add(input.mergeObject(null, Award.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, ActivityConfigOneFuLi message) throws IOException
        {
            if(message.level == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.level, false);

            if(message.vipLevel == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.vipLevel, false);

            if(message.award != null)
            {
                for(Award award : message.award)
                {
                    if(award != null)
                        output.writeObject(3, award, Award.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "level";
                case 2: return "vipLevel";
                case 3: return "award";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("level", 1);
            fieldMap.put("vipLevel", 2);
            fieldMap.put("award", 3);
        }
    };
    
}
