// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class DBActivityLotteryWheelOne implements Externalizable, Message<DBActivityLotteryWheelOne>
{

    public static Schema<DBActivityLotteryWheelOne> getSchema()
    {
        return SCHEMA;
    }

    public static DBActivityLotteryWheelOne getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBActivityLotteryWheelOne DEFAULT_INSTANCE = new DBActivityLotteryWheelOne();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer templateId;
    Integer count;
    Integer rate;

    public DBActivityLotteryWheelOne()
    {

    }

    public DBActivityLotteryWheelOne(
        Integer templateId,
        Integer count,
        Integer rate
    )
    {
        this.templateId = templateId;
        this.count = count;
        this.rate = rate;
    }

    // getters and setters

    // templateId

    public Integer getTemplateId()
    {
        return templateId;
    }


    public void setTemplateId(Integer templateId)
    {
        this.templateId = templateId;
    }

    // count

    public Integer getCount()
    {
        return count;
    }


    public void setCount(Integer count)
    {
        this.count = count;
    }

    // rate

    public Integer getRate()
    {
        return rate;
    }


    public void setRate(Integer rate)
    {
        this.rate = rate;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBActivityLotteryWheelOne> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBActivityLotteryWheelOne> SCHEMA = new Schema<DBActivityLotteryWheelOne>()
    {
        // schema methods

        public DBActivityLotteryWheelOne newMessage()
        {
            return new DBActivityLotteryWheelOne();
        }

        public Class<DBActivityLotteryWheelOne> typeClass()
        {
            return DBActivityLotteryWheelOne.class;
        }

        public String messageName()
        {
            return DBActivityLotteryWheelOne.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBActivityLotteryWheelOne.class.getName();
        }

        public boolean isInitialized(DBActivityLotteryWheelOne message)
        {
            return 
                message.templateId != null 
                && message.count != null 
                && message.rate != null;
        }

        public void mergeFrom(Input input, DBActivityLotteryWheelOne message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.templateId = input.readInt32();
                        break;
                    case 2:
                        message.count = input.readInt32();
                        break;
                    case 3:
                        message.rate = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBActivityLotteryWheelOne message) throws IOException
        {
            if(message.templateId == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.templateId, false);

            if(message.count == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.count, false);

            if(message.rate == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(3, message.rate, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "templateId";
                case 2: return "count";
                case 3: return "rate";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("templateId", 1);
            fieldMap.put("count", 2);
            fieldMap.put("rate", 3);
        }
    };
    
}
