// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBActivityAwardDouble implements Externalizable, Message<DBActivityAwardDouble>
{

    public static Schema<DBActivityAwardDouble> getSchema()
    {
        return SCHEMA;
    }

    public static DBActivityAwardDouble getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBActivityAwardDouble DEFAULT_INSTANCE = new DBActivityAwardDouble();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<AwardDouble> awardDouble;

    public DBActivityAwardDouble()
    {

    }

    // getters and setters

    // awardDouble

    public List<AwardDouble> getAwardDoubleList()
    {
        return awardDouble;
    }


    public void setAwardDoubleList(List<AwardDouble> awardDouble)
    {
        this.awardDouble = awardDouble;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBActivityAwardDouble> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBActivityAwardDouble> SCHEMA = new Schema<DBActivityAwardDouble>()
    {
        // schema methods

        public DBActivityAwardDouble newMessage()
        {
            return new DBActivityAwardDouble();
        }

        public Class<DBActivityAwardDouble> typeClass()
        {
            return DBActivityAwardDouble.class;
        }

        public String messageName()
        {
            return DBActivityAwardDouble.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBActivityAwardDouble.class.getName();
        }

        public boolean isInitialized(DBActivityAwardDouble message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBActivityAwardDouble message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.awardDouble == null)
                            message.awardDouble = new ArrayList<AwardDouble>();
                        message.awardDouble.add(input.mergeObject(null, AwardDouble.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBActivityAwardDouble message) throws IOException
        {
            if(message.awardDouble != null)
            {
                for(AwardDouble awardDouble : message.awardDouble)
                {
                    if(awardDouble != null)
                        output.writeObject(1, awardDouble, AwardDouble.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "awardDouble";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("awardDouble", 1);
        }
    };
    
}
