// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBActivityChengZhangJiJin implements Externalizable, Message<DBActivityChengZhangJiJin>
{

    public static Schema<DBActivityChengZhangJiJin> getSchema()
    {
        return SCHEMA;
    }

    public static DBActivityChengZhangJiJin getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBActivityChengZhangJiJin DEFAULT_INSTANCE = new DBActivityChengZhangJiJin();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<Integer> diamondDaily;

    public DBActivityChengZhangJiJin()
    {

    }

    // getters and setters

    // diamondDaily

    public List<Integer> getDiamondDailyList()
    {
        return diamondDaily;
    }


    public void setDiamondDailyList(List<Integer> diamondDaily)
    {
        this.diamondDaily = diamondDaily;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBActivityChengZhangJiJin> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBActivityChengZhangJiJin> SCHEMA = new Schema<DBActivityChengZhangJiJin>()
    {
        // schema methods

        public DBActivityChengZhangJiJin newMessage()
        {
            return new DBActivityChengZhangJiJin();
        }

        public Class<DBActivityChengZhangJiJin> typeClass()
        {
            return DBActivityChengZhangJiJin.class;
        }

        public String messageName()
        {
            return DBActivityChengZhangJiJin.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBActivityChengZhangJiJin.class.getName();
        }

        public boolean isInitialized(DBActivityChengZhangJiJin message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBActivityChengZhangJiJin message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.diamondDaily == null)
                            message.diamondDaily = new ArrayList<Integer>();
                        message.diamondDaily.add(input.readInt32());break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBActivityChengZhangJiJin message) throws IOException
        {
            if(message.diamondDaily != null)
            {
                for(Integer diamondDaily : message.diamondDaily)
                {
                    if(diamondDaily != null)
                        output.writeInt32(1, diamondDaily, true);
                }
            }
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "diamondDaily";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("diamondDaily", 1);
        }
    };
    
}
