// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBActivityPlayerHeroLibao implements Externalizable, Message<DBActivityPlayerHeroLibao>
{

    public static Schema<DBActivityPlayerHeroLibao> getSchema()
    {
        return SCHEMA;
    }

    public static DBActivityPlayerHeroLibao getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBActivityPlayerHeroLibao DEFAULT_INSTANCE = new DBActivityPlayerHeroLibao();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<Integer> rechargeId;
    List<Integer> buyCount;

    public DBActivityPlayerHeroLibao()
    {

    }

    // getters and setters

    // rechargeId

    public List<Integer> getRechargeIdList()
    {
        return rechargeId;
    }


    public void setRechargeIdList(List<Integer> rechargeId)
    {
        this.rechargeId = rechargeId;
    }

    // buyCount

    public List<Integer> getBuyCountList()
    {
        return buyCount;
    }


    public void setBuyCountList(List<Integer> buyCount)
    {
        this.buyCount = buyCount;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBActivityPlayerHeroLibao> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBActivityPlayerHeroLibao> SCHEMA = new Schema<DBActivityPlayerHeroLibao>()
    {
        // schema methods

        public DBActivityPlayerHeroLibao newMessage()
        {
            return new DBActivityPlayerHeroLibao();
        }

        public Class<DBActivityPlayerHeroLibao> typeClass()
        {
            return DBActivityPlayerHeroLibao.class;
        }

        public String messageName()
        {
            return DBActivityPlayerHeroLibao.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBActivityPlayerHeroLibao.class.getName();
        }

        public boolean isInitialized(DBActivityPlayerHeroLibao message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBActivityPlayerHeroLibao message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.rechargeId == null)
                            message.rechargeId = new ArrayList<Integer>();
                        message.rechargeId.add(input.readInt32());break;
                    case 2:
                        if(message.buyCount == null)
                            message.buyCount = new ArrayList<Integer>();
                        message.buyCount.add(input.readInt32());break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBActivityPlayerHeroLibao message) throws IOException
        {
            if(message.rechargeId != null)
            {
                for(Integer rechargeId : message.rechargeId)
                {
                    if(rechargeId != null)
                        output.writeInt32(1, rechargeId, true);
                }
            }

            if(message.buyCount != null)
            {
                for(Integer buyCount : message.buyCount)
                {
                    if(buyCount != null)
                        output.writeInt32(2, buyCount, true);
                }
            }
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "rechargeId";
                case 2: return "buyCount";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("rechargeId", 1);
            fieldMap.put("buyCount", 2);
        }
    };
    
}
