// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBRechargeAward implements Externalizable, Message<DBRechargeAward>
{

    public static Schema<DBRechargeAward> getSchema()
    {
        return SCHEMA;
    }

    public static DBRechargeAward getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBRechargeAward DEFAULT_INSTANCE = new DBRechargeAward();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<ActivityConfigOne> items;

    public DBRechargeAward()
    {

    }

    // getters and setters

    // items

    public List<ActivityConfigOne> getItemsList()
    {
        return items;
    }


    public void setItemsList(List<ActivityConfigOne> items)
    {
        this.items = items;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBRechargeAward> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBRechargeAward> SCHEMA = new Schema<DBRechargeAward>()
    {
        // schema methods

        public DBRechargeAward newMessage()
        {
            return new DBRechargeAward();
        }

        public Class<DBRechargeAward> typeClass()
        {
            return DBRechargeAward.class;
        }

        public String messageName()
        {
            return DBRechargeAward.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBRechargeAward.class.getName();
        }

        public boolean isInitialized(DBRechargeAward message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBRechargeAward message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.items == null)
                            message.items = new ArrayList<ActivityConfigOne>();
                        message.items.add(input.mergeObject(null, ActivityConfigOne.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBRechargeAward message) throws IOException
        {
            if(message.items != null)
            {
                for(ActivityConfigOne items : message.items)
                {
                    if(items != null)
                        output.writeObject(1, items, ActivityConfigOne.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "items";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("items", 1);
        }
    };
    
}
