// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class LevelAward implements Externalizable, Message<LevelAward>
{

    public static Schema<LevelAward> getSchema()
    {
        return SCHEMA;
    }

    public static LevelAward getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final LevelAward DEFAULT_INSTANCE = new LevelAward();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer level;
    List<Award> award;

    public LevelAward()
    {

    }

    public LevelAward(
        Integer level
    )
    {
        this.level = level;
    }

    // getters and setters

    // level

    public Integer getLevel()
    {
        return level;
    }


    public void setLevel(Integer level)
    {
        this.level = level;
    }

    // award

    public List<Award> getAwardList()
    {
        return award;
    }


    public void setAwardList(List<Award> award)
    {
        this.award = award;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<LevelAward> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<LevelAward> SCHEMA = new Schema<LevelAward>()
    {
        // schema methods

        public LevelAward newMessage()
        {
            return new LevelAward();
        }

        public Class<LevelAward> typeClass()
        {
            return LevelAward.class;
        }

        public String messageName()
        {
            return LevelAward.class.getSimpleName();
        }

        public String messageFullName()
        {
            return LevelAward.class.getName();
        }

        public boolean isInitialized(LevelAward message)
        {
            return 
                message.level != null;
        }

        public void mergeFrom(Input input, LevelAward message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.level = input.readInt32();
                        break;
                    case 2:
                        if(message.award == null)
                            message.award = new ArrayList<Award>();
                        message.award.add(input.mergeObject(null, Award.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, LevelAward message) throws IOException
        {
            if(message.level == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.level, false);

            if(message.award != null)
            {
                for(Award award : message.award)
                {
                    if(award != null)
                        output.writeObject(2, award, Award.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "level";
                case 2: return "award";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("level", 1);
            fieldMap.put("award", 2);
        }
    };
    
}
