// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.db.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DbChongZhiBang implements Externalizable, Message<DbChongZhiBang>
{

    public static Schema<DbChongZhiBang> getSchema()
    {
        return SCHEMA;
    }

    public static DbChongZhiBang getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DbChongZhiBang DEFAULT_INSTANCE = new DbChongZhiBang();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<DbChongZhiBangPlayer> playerInfo;

    public DbChongZhiBang()
    {

    }

    // getters and setters

    // playerInfo

    public List<DbChongZhiBangPlayer> getPlayerInfoList()
    {
        return playerInfo;
    }


    public void setPlayerInfoList(List<DbChongZhiBangPlayer> playerInfo)
    {
        this.playerInfo = playerInfo;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DbChongZhiBang> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DbChongZhiBang> SCHEMA = new Schema<DbChongZhiBang>()
    {
        // schema methods

        public DbChongZhiBang newMessage()
        {
            return new DbChongZhiBang();
        }

        public Class<DbChongZhiBang> typeClass()
        {
            return DbChongZhiBang.class;
        }

        public String messageName()
        {
            return DbChongZhiBang.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DbChongZhiBang.class.getName();
        }

        public boolean isInitialized(DbChongZhiBang message)
        {
            return true;
        }

        public void mergeFrom(Input input, DbChongZhiBang message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.playerInfo == null)
                            message.playerInfo = new ArrayList<DbChongZhiBangPlayer>();
                        message.playerInfo.add(input.mergeObject(null, DbChongZhiBangPlayer.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DbChongZhiBang message) throws IOException
        {
            if(message.playerInfo != null)
            {
                for(DbChongZhiBangPlayer playerInfo : message.playerInfo)
                {
                    if(playerInfo != null)
                        output.writeObject(1, playerInfo, DbChongZhiBangPlayer.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "playerInfo";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("playerInfo", 1);
        }
    };
    
}
