// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.db.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class DbChongZhiBangPlayer implements Externalizable, Message<DbChongZhiBangPlayer>
{

    public static Schema<DbChongZhiBangPlayer> getSchema()
    {
        return SCHEMA;
    }

    public static DbChongZhiBangPlayer getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DbChongZhiBangPlayer DEFAULT_INSTANCE = new DbChongZhiBangPlayer();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer playerId;
    Integer val;

    public DbChongZhiBangPlayer()
    {

    }

    public DbChongZhiBangPlayer(
        Integer playerId,
        Integer val
    )
    {
        this.playerId = playerId;
        this.val = val;
    }

    // getters and setters

    // playerId

    public Integer getPlayerId()
    {
        return playerId;
    }


    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }

    // val

    public Integer getVal()
    {
        return val;
    }


    public void setVal(Integer val)
    {
        this.val = val;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DbChongZhiBangPlayer> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DbChongZhiBangPlayer> SCHEMA = new Schema<DbChongZhiBangPlayer>()
    {
        // schema methods

        public DbChongZhiBangPlayer newMessage()
        {
            return new DbChongZhiBangPlayer();
        }

        public Class<DbChongZhiBangPlayer> typeClass()
        {
            return DbChongZhiBangPlayer.class;
        }

        public String messageName()
        {
            return DbChongZhiBangPlayer.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DbChongZhiBangPlayer.class.getName();
        }

        public boolean isInitialized(DbChongZhiBangPlayer message)
        {
            return 
                message.playerId != null 
                && message.val != null;
        }

        public void mergeFrom(Input input, DbChongZhiBangPlayer message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.playerId = input.readInt32();
                        break;
                    case 2:
                        message.val = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DbChongZhiBangPlayer message) throws IOException
        {
            if(message.playerId == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.playerId, false);

            if(message.val == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.val, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "playerId";
                case 2: return "val";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("playerId", 1);
            fieldMap.put("val", 2);
        }
    };
    
}
