// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.db.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBFriendHelpChannel implements Externalizable, Message<DBFriendHelpChannel>
{

    public static Schema<DBFriendHelpChannel> getSchema()
    {
        return SCHEMA;
    }

    public static DBFriendHelpChannel getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBFriendHelpChannel DEFAULT_INSTANCE = new DBFriendHelpChannel();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<DBFriendHelpItem> heroItem;

    public DBFriendHelpChannel()
    {

    }

    // getters and setters

    // heroItem

    public List<DBFriendHelpItem> getHeroItemList()
    {
        return heroItem;
    }


    public void setHeroItemList(List<DBFriendHelpItem> heroItem)
    {
        this.heroItem = heroItem;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBFriendHelpChannel> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBFriendHelpChannel> SCHEMA = new Schema<DBFriendHelpChannel>()
    {
        // schema methods

        public DBFriendHelpChannel newMessage()
        {
            return new DBFriendHelpChannel();
        }

        public Class<DBFriendHelpChannel> typeClass()
        {
            return DBFriendHelpChannel.class;
        }

        public String messageName()
        {
            return DBFriendHelpChannel.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBFriendHelpChannel.class.getName();
        }

        public boolean isInitialized(DBFriendHelpChannel message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBFriendHelpChannel message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.heroItem == null)
                            message.heroItem = new ArrayList<DBFriendHelpItem>();
                        message.heroItem.add(input.mergeObject(null, DBFriendHelpItem.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBFriendHelpChannel message) throws IOException
        {
            if(message.heroItem != null)
            {
                for(DBFriendHelpItem heroItem : message.heroItem)
                {
                    if(heroItem != null)
                        output.writeObject(1, heroItem, DBFriendHelpItem.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "heroItem";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("heroItem", 1);
        }
    };
    
}
