// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.db.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBFriendBuilding implements Externalizable, Message<DBFriendBuilding>
{

    public static Schema<DBFriendBuilding> getSchema()
    {
        return SCHEMA;
    }

    public static DBFriendBuilding getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBFriendBuilding DEFAULT_INSTANCE = new DBFriendBuilding();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<DBFriendBuildingItem> buildingItem;

    public DBFriendBuilding()
    {

    }

    // getters and setters

    // buildingItem

    public List<DBFriendBuildingItem> getBuildingItemList()
    {
        return buildingItem;
    }


    public void setBuildingItemList(List<DBFriendBuildingItem> buildingItem)
    {
        this.buildingItem = buildingItem;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBFriendBuilding> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBFriendBuilding> SCHEMA = new Schema<DBFriendBuilding>()
    {
        // schema methods

        public DBFriendBuilding newMessage()
        {
            return new DBFriendBuilding();
        }

        public Class<DBFriendBuilding> typeClass()
        {
            return DBFriendBuilding.class;
        }

        public String messageName()
        {
            return DBFriendBuilding.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBFriendBuilding.class.getName();
        }

        public boolean isInitialized(DBFriendBuilding message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBFriendBuilding message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.buildingItem == null)
                            message.buildingItem = new ArrayList<DBFriendBuildingItem>();
                        message.buildingItem.add(input.mergeObject(null, DBFriendBuildingItem.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBFriendBuilding message) throws IOException
        {
            if(message.buildingItem != null)
            {
                for(DBFriendBuildingItem buildingItem : message.buildingItem)
                {
                    if(buildingItem != null)
                        output.writeObject(1, buildingItem, DBFriendBuildingItem.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "buildingItem";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("buildingItem", 1);
        }
    };
    
}
