// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.db.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class DBQZYBPlayer1 implements Externalizable, Message<DBQZYBPlayer1>
{

    public static Schema<DBQZYBPlayer1> getSchema()
    {
        return SCHEMA;
    }

    public static DBQZYBPlayer1 getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBQZYBPlayer1 DEFAULT_INSTANCE = new DBQZYBPlayer1();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer playerId;
    String playerName;
    Integer count;
    Integer lastBuyTime;

    public DBQZYBPlayer1()
    {

    }

    public DBQZYBPlayer1(
        Integer playerId,
        String playerName,
        Integer count,
        Integer lastBuyTime
    )
    {
        this.playerId = playerId;
        this.playerName = playerName;
        this.count = count;
        this.lastBuyTime = lastBuyTime;
    }

    // getters and setters

    // playerId

    public Integer getPlayerId()
    {
        return playerId;
    }


    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }

    // playerName

    public String getPlayerName()
    {
        return playerName;
    }


    public void setPlayerName(String playerName)
    {
        this.playerName = playerName;
    }

    // count

    public Integer getCount()
    {
        return count;
    }


    public void setCount(Integer count)
    {
        this.count = count;
    }

    // lastBuyTime

    public Integer getLastBuyTime()
    {
        return lastBuyTime;
    }


    public void setLastBuyTime(Integer lastBuyTime)
    {
        this.lastBuyTime = lastBuyTime;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBQZYBPlayer1> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBQZYBPlayer1> SCHEMA = new Schema<DBQZYBPlayer1>()
    {
        // schema methods

        public DBQZYBPlayer1 newMessage()
        {
            return new DBQZYBPlayer1();
        }

        public Class<DBQZYBPlayer1> typeClass()
        {
            return DBQZYBPlayer1.class;
        }

        public String messageName()
        {
            return DBQZYBPlayer1.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBQZYBPlayer1.class.getName();
        }

        public boolean isInitialized(DBQZYBPlayer1 message)
        {
            return 
                message.playerId != null 
                && message.playerName != null 
                && message.count != null 
                && message.lastBuyTime != null;
        }

        public void mergeFrom(Input input, DBQZYBPlayer1 message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.playerId = input.readInt32();
                        break;
                    case 2:
                        message.playerName = input.readString();
                        break;
                    case 3:
                        message.count = input.readInt32();
                        break;
                    case 4:
                        message.lastBuyTime = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBQZYBPlayer1 message) throws IOException
        {
            if(message.playerId == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.playerId, false);

            if(message.playerName == null)
                throw new UninitializedMessageException(message);
            output.writeString(2, message.playerName, false);

            if(message.count == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(3, message.count, false);

            if(message.lastBuyTime == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(4, message.lastBuyTime, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "playerId";
                case 2: return "playerName";
                case 3: return "count";
                case 4: return "lastBuyTime";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("playerId", 1);
            fieldMap.put("playerName", 2);
            fieldMap.put("count", 3);
            fieldMap.put("lastBuyTime", 4);
        }
    };
    
}
