// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
@Generated("java_bean")
public final class ActivityFirstRechgeDouble implements Externalizable, Message<ActivityFirstRechgeDouble>
{

    public static Schema<ActivityFirstRechgeDouble> getSchema()
    {
        return SCHEMA;
    }

    public static ActivityFirstRechgeDouble getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ActivityFirstRechgeDouble DEFAULT_INSTANCE = new ActivityFirstRechgeDouble();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer rechargeId;
    Integer favorRate;

    public ActivityFirstRechgeDouble()
    {

    }

    public ActivityFirstRechgeDouble(
        Integer rechargeId,
        Integer favorRate
    )
    {
        this.rechargeId = rechargeId;
        this.favorRate = favorRate;
    }

    // getters and setters

    // rechargeId

    public Integer getRechargeId()
    {
        return rechargeId;
    }


    public void setRechargeId(Integer rechargeId)
    {
        this.rechargeId = rechargeId;
    }

    // favorRate

    public Integer getFavorRate()
    {
        return favorRate;
    }


    public void setFavorRate(Integer favorRate)
    {
        this.favorRate = favorRate;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<ActivityFirstRechgeDouble> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<ActivityFirstRechgeDouble> SCHEMA = new Schema<ActivityFirstRechgeDouble>()
    {
        // schema methods

        public ActivityFirstRechgeDouble newMessage()
        {
            return new ActivityFirstRechgeDouble();
        }

        public Class<ActivityFirstRechgeDouble> typeClass()
        {
            return ActivityFirstRechgeDouble.class;
        }

        public String messageName()
        {
            return ActivityFirstRechgeDouble.class.getSimpleName();
        }

        public String messageFullName()
        {
            return ActivityFirstRechgeDouble.class.getName();
        }

        public boolean isInitialized(ActivityFirstRechgeDouble message)
        {
            return 
                message.rechargeId != null 
                && message.favorRate != null;
        }

        public void mergeFrom(Input input, ActivityFirstRechgeDouble message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.rechargeId = input.readInt32();
                        break;
                    case 2:
                        message.favorRate = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, ActivityFirstRechgeDouble message) throws IOException
        {
            if(message.rechargeId == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.rechargeId, false);

            if(message.favorRate == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.favorRate, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "rechargeId";
                case 2: return "favorRate";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("rechargeId", 1);
            fieldMap.put("favorRate", 2);
        }
    };
    
}
