// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
@Generated("java_bean")
public final class AwardDouble implements Externalizable, Message<AwardDouble>
{

    public static Schema<AwardDouble> getSchema()
    {
        return SCHEMA;
    }

    public static AwardDouble getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final AwardDouble DEFAULT_INSTANCE = new AwardDouble();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer moudelType;
    Integer multipleCnt;

    public AwardDouble()
    {

    }

    public AwardDouble(
        Integer moudelType,
        Integer multipleCnt
    )
    {
        this.moudelType = moudelType;
        this.multipleCnt = multipleCnt;
    }

    // getters and setters

    // moudelType

    public Integer getMoudelType()
    {
        return moudelType;
    }


    public void setMoudelType(Integer moudelType)
    {
        this.moudelType = moudelType;
    }

    // multipleCnt

    public Integer getMultipleCnt()
    {
        return multipleCnt;
    }


    public void setMultipleCnt(Integer multipleCnt)
    {
        this.multipleCnt = multipleCnt;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<AwardDouble> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<AwardDouble> SCHEMA = new Schema<AwardDouble>()
    {
        // schema methods

        public AwardDouble newMessage()
        {
            return new AwardDouble();
        }

        public Class<AwardDouble> typeClass()
        {
            return AwardDouble.class;
        }

        public String messageName()
        {
            return AwardDouble.class.getSimpleName();
        }

        public String messageFullName()
        {
            return AwardDouble.class.getName();
        }

        public boolean isInitialized(AwardDouble message)
        {
            return 
                message.moudelType != null 
                && message.multipleCnt != null;
        }

        public void mergeFrom(Input input, AwardDouble message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.moudelType = input.readInt32();
                        break;
                    case 2:
                        message.multipleCnt = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, AwardDouble message) throws IOException
        {
            if(message.moudelType == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.moudelType, false);

            if(message.multipleCnt == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.multipleCnt, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "moudelType";
                case 2: return "multipleCnt";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("moudelType", 1);
            fieldMap.put("multipleCnt", 2);
        }
    };
    
}
