// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

@Generated("java_bean")
public final class DBActivitySale implements Externalizable, Message<DBActivitySale>
{

    public static Schema<DBActivitySale> getSchema()
    {
        return SCHEMA;
    }

    public static DBActivitySale getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBActivitySale DEFAULT_INSTANCE = new DBActivitySale();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<Sale> sale;

    public DBActivitySale()
    {

    }

    // getters and setters

    // sale

    public List<Sale> getSaleList()
    {
        return sale;
    }


    public void setSaleList(List<Sale> sale)
    {
        this.sale = sale;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBActivitySale> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBActivitySale> SCHEMA = new Schema<DBActivitySale>()
    {
        // schema methods

        public DBActivitySale newMessage()
        {
            return new DBActivitySale();
        }

        public Class<DBActivitySale> typeClass()
        {
            return DBActivitySale.class;
        }

        public String messageName()
        {
            return DBActivitySale.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBActivitySale.class.getName();
        }

        public boolean isInitialized(DBActivitySale message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBActivitySale message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.sale == null)
                            message.sale = new ArrayList<Sale>();
                        message.sale.add(input.mergeObject(null, Sale.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBActivitySale message) throws IOException
        {
            if(message.sale != null)
            {
                for(Sale sale : message.sale)
                {
                    if(sale != null)
                        output.writeObject(1, sale, Sale.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "sale";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("sale", 1);
        }
    };
    
}
