// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
@Generated("java_bean")
public final class DBActivityLevelAward implements Externalizable, Message<DBActivityLevelAward>
{

    public static Schema<DBActivityLevelAward> getSchema()
    {
        return SCHEMA;
    }

    public static DBActivityLevelAward getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBActivityLevelAward DEFAULT_INSTANCE = new DBActivityLevelAward();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<LevelAward> levelAward;
    Integer dayCount;

    public DBActivityLevelAward()
    {

    }

    public DBActivityLevelAward(
        Integer dayCount
    )
    {
        this.dayCount = dayCount;
    }

    // getters and setters

    // levelAward

    public List<LevelAward> getLevelAwardList()
    {
        return levelAward;
    }


    public void setLevelAwardList(List<LevelAward> levelAward)
    {
        this.levelAward = levelAward;
    }

    // dayCount

    public Integer getDayCount()
    {
        return dayCount;
    }


    public void setDayCount(Integer dayCount)
    {
        this.dayCount = dayCount;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBActivityLevelAward> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBActivityLevelAward> SCHEMA = new Schema<DBActivityLevelAward>()
    {
        // schema methods

        public DBActivityLevelAward newMessage()
        {
            return new DBActivityLevelAward();
        }

        public Class<DBActivityLevelAward> typeClass()
        {
            return DBActivityLevelAward.class;
        }

        public String messageName()
        {
            return DBActivityLevelAward.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBActivityLevelAward.class.getName();
        }

        public boolean isInitialized(DBActivityLevelAward message)
        {
            return 
                message.dayCount != null;
        }

        public void mergeFrom(Input input, DBActivityLevelAward message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.levelAward == null)
                            message.levelAward = new ArrayList<LevelAward>();
                        message.levelAward.add(input.mergeObject(null, LevelAward.getSchema()));
                        break;

                    case 2:
                        message.dayCount = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBActivityLevelAward message) throws IOException
        {
            if(message.levelAward != null)
            {
                for(LevelAward levelAward : message.levelAward)
                {
                    if(levelAward != null)
                        output.writeObject(1, levelAward, LevelAward.getSchema(), true);
                }
            }


            if(message.dayCount == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.dayCount, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "levelAward";
                case 2: return "dayCount";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("levelAward", 1);
            fieldMap.put("dayCount", 2);
        }
    };
    
}
