// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

@Generated("java_bean")
public final class DBActivityLevel implements Externalizable, Message<DBActivityLevel>
{

    public static Schema<DBActivityLevel> getSchema()
    {
        return SCHEMA;
    }

    public static DBActivityLevel getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBActivityLevel DEFAULT_INSTANCE = new DBActivityLevel();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<Integer> awardedLevel;

    public DBActivityLevel()
    {

    }

    // getters and setters

    // awardedLevel

    public List<Integer> getAwardedLevelList()
    {
        return awardedLevel;
    }


    public void setAwardedLevelList(List<Integer> awardedLevel)
    {
        this.awardedLevel = awardedLevel;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBActivityLevel> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBActivityLevel> SCHEMA = new Schema<DBActivityLevel>()
    {
        // schema methods

        public DBActivityLevel newMessage()
        {
            return new DBActivityLevel();
        }

        public Class<DBActivityLevel> typeClass()
        {
            return DBActivityLevel.class;
        }

        public String messageName()
        {
            return DBActivityLevel.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBActivityLevel.class.getName();
        }

        public boolean isInitialized(DBActivityLevel message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBActivityLevel message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.awardedLevel == null)
                            message.awardedLevel = new ArrayList<Integer>();
                        message.awardedLevel.add(input.readInt32());break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBActivityLevel message) throws IOException
        {
            if(message.awardedLevel != null)
            {
                for(Integer awardedLevel : message.awardedLevel)
                {
                    if(awardedLevel != null)
                        output.writeInt32(1, awardedLevel, true);
                }
            }
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "awardedLevel";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("awardedLevel", 1);
        }
    };
    
}
