// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

@Generated("java_bean")
public final class DBActivityHeroLibao implements Externalizable, Message<DBActivityHeroLibao>
{

    public static Schema<DBActivityHeroLibao> getSchema()
    {
        return SCHEMA;
    }

    public static DBActivityHeroLibao getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBActivityHeroLibao DEFAULT_INSTANCE = new DBActivityHeroLibao();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<ActivityConfigHeroLiBao> items;

    public DBActivityHeroLibao()
    {

    }

    // getters and setters

    // items

    public List<ActivityConfigHeroLiBao> getItemsList()
    {
        return items;
    }


    public void setItemsList(List<ActivityConfigHeroLiBao> items)
    {
        this.items = items;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBActivityHeroLibao> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBActivityHeroLibao> SCHEMA = new Schema<DBActivityHeroLibao>()
    {
        // schema methods

        public DBActivityHeroLibao newMessage()
        {
            return new DBActivityHeroLibao();
        }

        public Class<DBActivityHeroLibao> typeClass()
        {
            return DBActivityHeroLibao.class;
        }

        public String messageName()
        {
            return DBActivityHeroLibao.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBActivityHeroLibao.class.getName();
        }

        public boolean isInitialized(DBActivityHeroLibao message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBActivityHeroLibao message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.items == null)
                            message.items = new ArrayList<ActivityConfigHeroLiBao>();
                        message.items.add(input.mergeObject(null, ActivityConfigHeroLiBao.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBActivityHeroLibao message) throws IOException
        {
            if(message.items != null)
            {
                for(ActivityConfigHeroLiBao items : message.items)
                {
                    if(items != null)
                        output.writeObject(1, items, ActivityConfigHeroLiBao.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "items";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("items", 1);
        }
    };
    
}
