// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

@Generated("java_bean")
public final class DBActivityFirstRechgeDouble implements Externalizable, Message<DBActivityFirstRechgeDouble>
{

    public static Schema<DBActivityFirstRechgeDouble> getSchema()
    {
        return SCHEMA;
    }

    public static DBActivityFirstRechgeDouble getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBActivityFirstRechgeDouble DEFAULT_INSTANCE = new DBActivityFirstRechgeDouble();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<ActivityFirstRechgeDouble> items;

    public DBActivityFirstRechgeDouble()
    {

    }

    // getters and setters

    // items

    public List<ActivityFirstRechgeDouble> getItemsList()
    {
        return items;
    }


    public void setItemsList(List<ActivityFirstRechgeDouble> items)
    {
        this.items = items;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBActivityFirstRechgeDouble> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBActivityFirstRechgeDouble> SCHEMA = new Schema<DBActivityFirstRechgeDouble>()
    {
        // schema methods

        public DBActivityFirstRechgeDouble newMessage()
        {
            return new DBActivityFirstRechgeDouble();
        }

        public Class<DBActivityFirstRechgeDouble> typeClass()
        {
            return DBActivityFirstRechgeDouble.class;
        }

        public String messageName()
        {
            return DBActivityFirstRechgeDouble.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBActivityFirstRechgeDouble.class.getName();
        }

        public boolean isInitialized(DBActivityFirstRechgeDouble message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBActivityFirstRechgeDouble message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.items == null)
                            message.items = new ArrayList<ActivityFirstRechgeDouble>();
                        message.items.add(input.mergeObject(null, ActivityFirstRechgeDouble.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBActivityFirstRechgeDouble message) throws IOException
        {
            if(message.items != null)
            {
                for(ActivityFirstRechgeDouble items : message.items)
                {
                    if(items != null)
                        output.writeObject(1, items, ActivityFirstRechgeDouble.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "items";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("items", 1);
        }
    };
    
}
