// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
@Generated("java_bean")
public final class DBActivityMine implements Externalizable, Message<DBActivityMine>
{

    public static Schema<DBActivityMine> getSchema()
    {
        return SCHEMA;
    }

    public static DBActivityMine getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBActivityMine DEFAULT_INSTANCE = new DBActivityMine();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer usedCount;

    public DBActivityMine()
    {

    }

    public DBActivityMine(
        Integer usedCount
    )
    {
        this.usedCount = usedCount;
    }

    // getters and setters

    // usedCount

    public Integer getUsedCount()
    {
        return usedCount;
    }


    public void setUsedCount(Integer usedCount)
    {
        this.usedCount = usedCount;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBActivityMine> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBActivityMine> SCHEMA = new Schema<DBActivityMine>()
    {
        // schema methods

        public DBActivityMine newMessage()
        {
            return new DBActivityMine();
        }

        public Class<DBActivityMine> typeClass()
        {
            return DBActivityMine.class;
        }

        public String messageName()
        {
            return DBActivityMine.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBActivityMine.class.getName();
        }

        public boolean isInitialized(DBActivityMine message)
        {
            return 
                message.usedCount != null;
        }

        public void mergeFrom(Input input, DBActivityMine message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.usedCount = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBActivityMine message) throws IOException
        {
            if(message.usedCount == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.usedCount, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "usedCount";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("usedCount", 1);
        }
    };
    
}
