// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.activity.bean;

import javax.annotation.Generated;
import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
@Generated("java_bean")
public final class Sale implements Externalizable, Message<Sale>
{

    public static Schema<Sale> getSchema()
    {
        return SCHEMA;
    }

    public static Sale getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final Sale DEFAULT_INSTANCE = new Sale();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer storeType;
    Integer saleResult;

    public Sale()
    {

    }

    public Sale(
        Integer storeType,
        Integer saleResult
    )
    {
        this.storeType = storeType;
        this.saleResult = saleResult;
    }

    // getters and setters

    // storeType

    public Integer getStoreType()
    {
        return storeType;
    }


    public void setStoreType(Integer storeType)
    {
        this.storeType = storeType;
    }

    // saleResult

    public Integer getSaleResult()
    {
        return saleResult;
    }


    public void setSaleResult(Integer saleResult)
    {
        this.saleResult = saleResult;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<Sale> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<Sale> SCHEMA = new Schema<Sale>()
    {
        // schema methods

        public Sale newMessage()
        {
            return new Sale();
        }

        public Class<Sale> typeClass()
        {
            return Sale.class;
        }

        public String messageName()
        {
            return Sale.class.getSimpleName();
        }

        public String messageFullName()
        {
            return Sale.class.getName();
        }

        public boolean isInitialized(Sale message)
        {
            return 
                message.storeType != null 
                && message.saleResult != null;
        }

        public void mergeFrom(Input input, Sale message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.storeType = input.readInt32();
                        break;
                    case 2:
                        message.saleResult = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, Sale message) throws IOException
        {
            if(message.storeType == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.storeType, false);

            if(message.saleResult == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.saleResult, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "storeType";
                case 2: return "saleResult";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("storeType", 1);
            fieldMap.put("saleResult", 2);
        }
    };
    
}
