// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.rank.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class DBPlayerLevelRank1 implements Externalizable, Message<DBPlayerLevelRank1>
{

    public static Schema<DBPlayerLevelRank1> getSchema()
    {
        return SCHEMA;
    }

    public static DBPlayerLevelRank1 getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBPlayerLevelRank1 DEFAULT_INSTANCE = new DBPlayerLevelRank1();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer playerId;
    Integer rankChange;

    public DBPlayerLevelRank1()
    {

    }

    public DBPlayerLevelRank1(
        Integer playerId,
        Integer rankChange
    )
    {
        this.playerId = playerId;
        this.rankChange = rankChange;
    }

    // getters and setters

    // playerId

    public Integer getPlayerId()
    {
        return playerId;
    }


    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }

    // rankChange

    public Integer getRankChange()
    {
        return rankChange;
    }


    public void setRankChange(Integer rankChange)
    {
        this.rankChange = rankChange;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBPlayerLevelRank1> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBPlayerLevelRank1> SCHEMA = new Schema<DBPlayerLevelRank1>()
    {
        // schema methods

        public DBPlayerLevelRank1 newMessage()
        {
            return new DBPlayerLevelRank1();
        }

        public Class<DBPlayerLevelRank1> typeClass()
        {
            return DBPlayerLevelRank1.class;
        }

        public String messageName()
        {
            return DBPlayerLevelRank1.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBPlayerLevelRank1.class.getName();
        }

        public boolean isInitialized(DBPlayerLevelRank1 message)
        {
            return 
                message.playerId != null 
                && message.rankChange != null;
        }

        public void mergeFrom(Input input, DBPlayerLevelRank1 message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.playerId = input.readInt32();
                        break;
                    case 2:
                        message.rankChange = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBPlayerLevelRank1 message) throws IOException
        {
            if(message.playerId == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.playerId, false);

            if(message.rankChange == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.rankChange, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "playerId";
                case 2: return "rankChange";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("playerId", 1);
            fieldMap.put("rankChange", 2);
        }
    };
    
}
