// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.rank.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class DBRankHeroStars1 implements Externalizable, Message<DBRankHeroStars1>
{

    public static Schema<DBRankHeroStars1> getSchema()
    {
        return SCHEMA;
    }

    public static DBRankHeroStars1 getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBRankHeroStars1 DEFAULT_INSTANCE = new DBRankHeroStars1();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer playerId;
    Integer starSum;
    Integer rankChange;
    List<game.module.battle.bean.DBStageHero> heros;

    public DBRankHeroStars1()
    {

    }

    public DBRankHeroStars1(
        Integer playerId,
        Integer starSum,
        Integer rankChange
    )
    {
        this.playerId = playerId;
        this.starSum = starSum;
        this.rankChange = rankChange;
    }

    // getters and setters

    // playerId

    public Integer getPlayerId()
    {
        return playerId;
    }


    public void setPlayerId(Integer playerId)
    {
        this.playerId = playerId;
    }

    // starSum

    public Integer getStarSum()
    {
        return starSum;
    }


    public void setStarSum(Integer starSum)
    {
        this.starSum = starSum;
    }

    // rankChange

    public Integer getRankChange()
    {
        return rankChange;
    }


    public void setRankChange(Integer rankChange)
    {
        this.rankChange = rankChange;
    }

    // heros

    public List<game.module.battle.bean.DBStageHero> getHerosList()
    {
        return heros;
    }


    public void setHerosList(List<game.module.battle.bean.DBStageHero> heros)
    {
        this.heros = heros;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBRankHeroStars1> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBRankHeroStars1> SCHEMA = new Schema<DBRankHeroStars1>()
    {
        // schema methods

        public DBRankHeroStars1 newMessage()
        {
            return new DBRankHeroStars1();
        }

        public Class<DBRankHeroStars1> typeClass()
        {
            return DBRankHeroStars1.class;
        }

        public String messageName()
        {
            return DBRankHeroStars1.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBRankHeroStars1.class.getName();
        }

        public boolean isInitialized(DBRankHeroStars1 message)
        {
            return 
                message.playerId != null 
                && message.starSum != null 
                && message.rankChange != null;
        }

        public void mergeFrom(Input input, DBRankHeroStars1 message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.playerId = input.readInt32();
                        break;
                    case 2:
                        message.starSum = input.readInt32();
                        break;
                    case 3:
                        message.rankChange = input.readInt32();
                        break;
                    case 4:
                        if(message.heros == null)
                            message.heros = new ArrayList<game.module.battle.bean.DBStageHero>();
                        message.heros.add(input.mergeObject(null, game.module.battle.bean.DBStageHero.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBRankHeroStars1 message) throws IOException
        {
            if(message.playerId == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.playerId, false);

            if(message.starSum == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.starSum, false);

            if(message.rankChange == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(3, message.rankChange, false);

            if(message.heros != null)
            {
                for(game.module.battle.bean.DBStageHero heros : message.heros)
                {
                    if(heros != null)
                        output.writeObject(4, heros, game.module.battle.bean.DBStageHero.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "playerId";
                case 2: return "starSum";
                case 3: return "rankChange";
                case 4: return "heros";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("playerId", 1);
            fieldMap.put("starSum", 2);
            fieldMap.put("rankChange", 3);
            fieldMap.put("heros", 4);
        }
    };
    
}
