// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: formation.proto

package db.proto;

public final class ProtoMessageFormation {
  private ProtoMessageFormation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DBBattlesetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:db.proto.DBBattleset)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 mythic = 1;</code>
     */
    int getMythic();

    /**
     * <pre>
     *城市的防守阵容
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
     */
    int getFormationGeneralsCount();
    /**
     * <pre>
     *城市的防守阵容
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
     */
    boolean containsFormationGenerals(
        int key);
    /**
     * Use {@link #getFormationGeneralsMap()} instead.
     */
    @Deprecated
    java.util.Map<Integer, Long>
    getFormationGenerals();
    /**
     * <pre>
     *城市的防守阵容
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
     */
    java.util.Map<Integer, Long>
    getFormationGeneralsMap();
    /**
     * <pre>
     *城市的防守阵容
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
     */

    long getFormationGeneralsOrDefault(
        int key,
        long defaultValue);
    /**
     * <pre>
     *城市的防守阵容
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
     */

    long getFormationGeneralsOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code db.proto.DBBattleset}
   */
  public  static final class DBBattleset extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:db.proto.DBBattleset)
      DBBattlesetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DBBattleset.newBuilder() to construct.
    private DBBattleset(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DBBattleset() {
      mythic_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DBBattleset(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              mythic_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                formationGenerals_ = com.google.protobuf.MapField.newMapField(
                    FormationGeneralsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<Integer, Long>
              formationGenerals__ = input.readMessage(
                  FormationGeneralsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              formationGenerals_.getMutableMap().put(
                  formationGenerals__.getKey(), formationGenerals__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMessageFormation.internal_static_db_proto_DBBattleset_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetFormationGenerals();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMessageFormation.internal_static_db_proto_DBBattleset_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DBBattleset.class, Builder.class);
    }

    private int bitField0_;
    public static final int MYTHIC_FIELD_NUMBER = 1;
    private int mythic_;
    /**
     * <code>int32 mythic = 1;</code>
     */
    public int getMythic() {
      return mythic_;
    }

    public static final int FORMATION_GENERALS_FIELD_NUMBER = 2;
    private static final class FormationGeneralsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          Integer, Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<Integer, Long>newDefaultInstance(
                  ProtoMessageFormation.internal_static_db_proto_DBBattleset_FormationGeneralsEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L);
    }
    private com.google.protobuf.MapField<
        Integer, Long> formationGenerals_;
    private com.google.protobuf.MapField<Integer, Long>
    internalGetFormationGenerals() {
      if (formationGenerals_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FormationGeneralsDefaultEntryHolder.defaultEntry);
      }
      return formationGenerals_;
    }

    public int getFormationGeneralsCount() {
      return internalGetFormationGenerals().getMap().size();
    }
    /**
     * <pre>
     *城市的防守阵容
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
     */

    public boolean containsFormationGenerals(
        int key) {
      
      return internalGetFormationGenerals().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFormationGeneralsMap()} instead.
     */
    @Deprecated
    public java.util.Map<Integer, Long> getFormationGenerals() {
      return getFormationGeneralsMap();
    }
    /**
     * <pre>
     *城市的防守阵容
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
     */

    public java.util.Map<Integer, Long> getFormationGeneralsMap() {
      return internalGetFormationGenerals().getMap();
    }
    /**
     * <pre>
     *城市的防守阵容
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
     */

    public long getFormationGeneralsOrDefault(
        int key,
        long defaultValue) {
      
      java.util.Map<Integer, Long> map =
          internalGetFormationGenerals().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *城市的防守阵容
     * </pre>
     *
     * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
     */

    public long getFormationGeneralsOrThrow(
        int key) {
      
      java.util.Map<Integer, Long> map =
          internalGetFormationGenerals().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mythic_ != 0) {
        output.writeInt32(1, mythic_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetFormationGenerals(),
          FormationGeneralsDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mythic_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, mythic_);
      }
      for (java.util.Map.Entry<Integer, Long> entry
           : internalGetFormationGenerals().getMap().entrySet()) {
        com.google.protobuf.MapEntry<Integer, Long>
        formationGenerals__ = FormationGeneralsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, formationGenerals__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DBBattleset)) {
        return super.equals(obj);
      }
      DBBattleset other = (DBBattleset) obj;

      boolean result = true;
      result = result && (getMythic()
          == other.getMythic());
      result = result && internalGetFormationGenerals().equals(
          other.internalGetFormationGenerals());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MYTHIC_FIELD_NUMBER;
      hash = (53 * hash) + getMythic();
      if (!internalGetFormationGenerals().getMap().isEmpty()) {
        hash = (37 * hash) + FORMATION_GENERALS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetFormationGenerals().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DBBattleset parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DBBattleset parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DBBattleset parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DBBattleset parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DBBattleset parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DBBattleset parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DBBattleset parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DBBattleset parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DBBattleset parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DBBattleset parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DBBattleset parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DBBattleset parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DBBattleset prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code db.proto.DBBattleset}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:db.proto.DBBattleset)
        DBBattlesetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMessageFormation.internal_static_db_proto_DBBattleset_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetFormationGenerals();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableFormationGenerals();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMessageFormation.internal_static_db_proto_DBBattleset_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DBBattleset.class, Builder.class);
      }

      // Construct using db.proto.ProtoMessageFormation.DBBattleset.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        mythic_ = 0;

        internalGetMutableFormationGenerals().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMessageFormation.internal_static_db_proto_DBBattleset_descriptor;
      }

      @Override
      public DBBattleset getDefaultInstanceForType() {
        return DBBattleset.getDefaultInstance();
      }

      @Override
      public DBBattleset build() {
        DBBattleset result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DBBattleset buildPartial() {
        DBBattleset result = new DBBattleset(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.mythic_ = mythic_;
        result.formationGenerals_ = internalGetFormationGenerals();
        result.formationGenerals_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DBBattleset) {
          return mergeFrom((DBBattleset)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DBBattleset other) {
        if (other == DBBattleset.getDefaultInstance()) return this;
        if (other.getMythic() != 0) {
          setMythic(other.getMythic());
        }
        internalGetMutableFormationGenerals().mergeFrom(
            other.internalGetFormationGenerals());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DBBattleset parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DBBattleset) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int mythic_ ;
      /**
       * <code>int32 mythic = 1;</code>
       */
      public int getMythic() {
        return mythic_;
      }
      /**
       * <code>int32 mythic = 1;</code>
       */
      public Builder setMythic(int value) {
        
        mythic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 mythic = 1;</code>
       */
      public Builder clearMythic() {
        
        mythic_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          Integer, Long> formationGenerals_;
      private com.google.protobuf.MapField<Integer, Long>
      internalGetFormationGenerals() {
        if (formationGenerals_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FormationGeneralsDefaultEntryHolder.defaultEntry);
        }
        return formationGenerals_;
      }
      private com.google.protobuf.MapField<Integer, Long>
      internalGetMutableFormationGenerals() {
        onChanged();;
        if (formationGenerals_ == null) {
          formationGenerals_ = com.google.protobuf.MapField.newMapField(
              FormationGeneralsDefaultEntryHolder.defaultEntry);
        }
        if (!formationGenerals_.isMutable()) {
          formationGenerals_ = formationGenerals_.copy();
        }
        return formationGenerals_;
      }

      public int getFormationGeneralsCount() {
        return internalGetFormationGenerals().getMap().size();
      }
      /**
       * <pre>
       *城市的防守阵容
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
       */

      public boolean containsFormationGenerals(
          int key) {
        
        return internalGetFormationGenerals().getMap().containsKey(key);
      }
      /**
       * Use {@link #getFormationGeneralsMap()} instead.
       */
      @Deprecated
      public java.util.Map<Integer, Long> getFormationGenerals() {
        return getFormationGeneralsMap();
      }
      /**
       * <pre>
       *城市的防守阵容
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
       */

      public java.util.Map<Integer, Long> getFormationGeneralsMap() {
        return internalGetFormationGenerals().getMap();
      }
      /**
       * <pre>
       *城市的防守阵容
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
       */

      public long getFormationGeneralsOrDefault(
          int key,
          long defaultValue) {
        
        java.util.Map<Integer, Long> map =
            internalGetFormationGenerals().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *城市的防守阵容
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
       */

      public long getFormationGeneralsOrThrow(
          int key) {
        
        java.util.Map<Integer, Long> map =
            internalGetFormationGenerals().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearFormationGenerals() {
        internalGetMutableFormationGenerals().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *城市的防守阵容
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
       */

      public Builder removeFormationGenerals(
          int key) {
        
        internalGetMutableFormationGenerals().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<Integer, Long>
      getMutableFormationGenerals() {
        return internalGetMutableFormationGenerals().getMutableMap();
      }
      /**
       * <pre>
       *城市的防守阵容
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
       */
      public Builder putFormationGenerals(
          int key,
          long value) {
        
        
        internalGetMutableFormationGenerals().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *城市的防守阵容
       * </pre>
       *
       * <code>map&lt;int32, int64&gt; formation_generals = 2;</code>
       */

      public Builder putAllFormationGenerals(
          java.util.Map<Integer, Long> values) {
        internalGetMutableFormationGenerals().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:db.proto.DBBattleset)
    }

    // @@protoc_insertion_point(class_scope:db.proto.DBBattleset)
    private static final DBBattleset DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DBBattleset();
    }

    public static DBBattleset getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DBBattleset>
        PARSER = new com.google.protobuf.AbstractParser<DBBattleset>() {
      @Override
      public DBBattleset parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DBBattleset(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DBBattleset> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DBBattleset> getParserForType() {
      return PARSER;
    }

    @Override
    public DBBattleset getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_db_proto_DBBattleset_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_db_proto_DBBattleset_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_db_proto_DBBattleset_FormationGeneralsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_db_proto_DBBattleset_FormationGeneralsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017formation.proto\022\010db.proto\"\241\001\n\013DBBattle" +
      "set\022\016\n\006mythic\030\001 \001(\005\022H\n\022formation_general" +
      "s\030\002 \003(\0132,.db.proto.DBBattleset.Formation" +
      "GeneralsEntry\0328\n\026FormationGeneralsEntry\022" +
      "\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\003:\0028\001B\031B\025Proto" +
      "MessageFormationH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_db_proto_DBBattleset_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_db_proto_DBBattleset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_db_proto_DBBattleset_descriptor,
        new String[] { "Mythic", "FormationGenerals", });
    internal_static_db_proto_DBBattleset_FormationGeneralsEntry_descriptor =
      internal_static_db_proto_DBBattleset_descriptor.getNestedTypes().get(0);
    internal_static_db_proto_DBBattleset_FormationGeneralsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_db_proto_DBBattleset_FormationGeneralsEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
