// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.battle.bean;



public enum DB_ENEMY_TYPE implements io.protostuff.EnumLite<DB_ENEMY_TYPE>
{
    DB_ENEMY_TYPE_ROBOT(1),
    DB_ENEMY_TYPE_PLAYER(2);
    
    public final int number;
    
    private DB_ENEMY_TYPE (int number)
    {
        this.number = number;
    }
    
    public int getNumber()
    {
        return number;
    }
    
    public static DB_ENEMY_TYPE valueOf(int number)
    {
        switch(number) 
        {
            case 1: return DB_ENEMY_TYPE_ROBOT;
            case 2: return DB_ENEMY_TYPE_PLAYER;
            default: return null;
        }
    }
}
