// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.battle.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBArena implements Externalizable, Message<DBArena>
{

    public static Schema<DBArena> getSchema()
    {
        return SCHEMA;
    }

    public static DBArena getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBArena DEFAULT_INSTANCE = new DBArena();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<DBArenaMember> memberRank;

    public DBArena()
    {

    }

    // getters and setters

    // memberRank

    public List<DBArenaMember> getMemberRankList()
    {
        return memberRank;
    }


    public void setMemberRankList(List<DBArenaMember> memberRank)
    {
        this.memberRank = memberRank;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBArena> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBArena> SCHEMA = new Schema<DBArena>()
    {
        // schema methods

        public DBArena newMessage()
        {
            return new DBArena();
        }

        public Class<DBArena> typeClass()
        {
            return DBArena.class;
        }

        public String messageName()
        {
            return DBArena.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBArena.class.getName();
        }

        public boolean isInitialized(DBArena message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBArena message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.memberRank == null)
                            message.memberRank = new ArrayList<DBArenaMember>();
                        message.memberRank.add(input.mergeObject(null, DBArenaMember.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBArena message) throws IOException
        {
            if(message.memberRank != null)
            {
                for(DBArenaMember memberRank : message.memberRank)
                {
                    if(memberRank != null)
                        output.writeObject(1, memberRank, DBArenaMember.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "memberRank";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("memberRank", 1);
        }
    };
    
}
