// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.battle.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class DBArenaBattleRecord implements Externalizable, Message<DBArenaBattleRecord>
{

    public static Schema<DBArenaBattleRecord> getSchema()
    {
        return SCHEMA;
    }

    public static DBArenaBattleRecord getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBArenaBattleRecord DEFAULT_INSTANCE = new DBArenaBattleRecord();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Boolean isWin;
    Integer rankChange;
    Boolean isAttacker;
    Integer attackTime;
    String targetName;

    public DBArenaBattleRecord()
    {

    }

    public DBArenaBattleRecord(
        Boolean isWin,
        Integer rankChange,
        Boolean isAttacker,
        Integer attackTime,
        String targetName
    )
    {
        this.isWin = isWin;
        this.rankChange = rankChange;
        this.isAttacker = isAttacker;
        this.attackTime = attackTime;
        this.targetName = targetName;
    }

    // getters and setters

    // isWin

    public Boolean getIsWin()
    {
        return isWin;
    }


    public void setIsWin(Boolean isWin)
    {
        this.isWin = isWin;
    }

    // rankChange

    public Integer getRankChange()
    {
        return rankChange;
    }


    public void setRankChange(Integer rankChange)
    {
        this.rankChange = rankChange;
    }

    // isAttacker

    public Boolean getIsAttacker()
    {
        return isAttacker;
    }


    public void setIsAttacker(Boolean isAttacker)
    {
        this.isAttacker = isAttacker;
    }

    // attackTime

    public Integer getAttackTime()
    {
        return attackTime;
    }


    public void setAttackTime(Integer attackTime)
    {
        this.attackTime = attackTime;
    }

    // targetName

    public String getTargetName()
    {
        return targetName;
    }


    public void setTargetName(String targetName)
    {
        this.targetName = targetName;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBArenaBattleRecord> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBArenaBattleRecord> SCHEMA = new Schema<DBArenaBattleRecord>()
    {
        // schema methods

        public DBArenaBattleRecord newMessage()
        {
            return new DBArenaBattleRecord();
        }

        public Class<DBArenaBattleRecord> typeClass()
        {
            return DBArenaBattleRecord.class;
        }

        public String messageName()
        {
            return DBArenaBattleRecord.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBArenaBattleRecord.class.getName();
        }

        public boolean isInitialized(DBArenaBattleRecord message)
        {
            return 
                message.isWin != null 
                && message.rankChange != null 
                && message.isAttacker != null 
                && message.attackTime != null 
                && message.targetName != null;
        }

        public void mergeFrom(Input input, DBArenaBattleRecord message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.isWin = input.readBool();
                        break;
                    case 2:
                        message.rankChange = input.readInt32();
                        break;
                    case 3:
                        message.isAttacker = input.readBool();
                        break;
                    case 4:
                        message.attackTime = input.readInt32();
                        break;
                    case 5:
                        message.targetName = input.readString();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBArenaBattleRecord message) throws IOException
        {
            if(message.isWin == null)
                throw new UninitializedMessageException(message);
            output.writeBool(1, message.isWin, false);

            if(message.rankChange == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.rankChange, false);

            if(message.isAttacker == null)
                throw new UninitializedMessageException(message);
            output.writeBool(3, message.isAttacker, false);

            if(message.attackTime == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(4, message.attackTime, false);

            if(message.targetName == null)
                throw new UninitializedMessageException(message);
            output.writeString(5, message.targetName, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "isWin";
                case 2: return "rankChange";
                case 3: return "isAttacker";
                case 4: return "attackTime";
                case 5: return "targetName";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("isWin", 1);
            fieldMap.put("rankChange", 2);
            fieldMap.put("isAttacker", 3);
            fieldMap.put("attackTime", 4);
            fieldMap.put("targetName", 5);
        }
    };
    
}
