// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.battle.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBArenaPack implements Externalizable, Message<DBArenaPack>
{

    public static Schema<DBArenaPack> getSchema()
    {
        return SCHEMA;
    }

    public static DBArenaPack getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBArenaPack DEFAULT_INSTANCE = new DBArenaPack();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<DBArenaRecentBattle> recentBattle;

    public DBArenaPack()
    {

    }

    // getters and setters

    // recentBattle

    public List<DBArenaRecentBattle> getRecentBattleList()
    {
        return recentBattle;
    }


    public void setRecentBattleList(List<DBArenaRecentBattle> recentBattle)
    {
        this.recentBattle = recentBattle;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBArenaPack> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBArenaPack> SCHEMA = new Schema<DBArenaPack>()
    {
        // schema methods

        public DBArenaPack newMessage()
        {
            return new DBArenaPack();
        }

        public Class<DBArenaPack> typeClass()
        {
            return DBArenaPack.class;
        }

        public String messageName()
        {
            return DBArenaPack.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBArenaPack.class.getName();
        }

        public boolean isInitialized(DBArenaPack message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBArenaPack message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.recentBattle == null)
                            message.recentBattle = new ArrayList<DBArenaRecentBattle>();
                        message.recentBattle.add(input.mergeObject(null, DBArenaRecentBattle.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBArenaPack message) throws IOException
        {
            if(message.recentBattle != null)
            {
                for(DBArenaRecentBattle recentBattle : message.recentBattle)
                {
                    if(recentBattle != null)
                        output.writeObject(1, recentBattle, DBArenaRecentBattle.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "recentBattle";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("recentBattle", 1);
        }
    };
    
}
