// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.battle.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBArenaOnePlayer implements Externalizable, Message<DBArenaOnePlayer>
{

    public static Schema<DBArenaOnePlayer> getSchema()
    {
        return SCHEMA;
    }

    public static DBArenaOnePlayer getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBArenaOnePlayer DEFAULT_INSTANCE = new DBArenaOnePlayer();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<Integer> defenceHeros;
    List<DBArenaBattleRecord> battleRecord;

    public DBArenaOnePlayer()
    {

    }

    // getters and setters

    // defenceHeros

    public List<Integer> getDefenceHerosList()
    {
        return defenceHeros;
    }


    public void setDefenceHerosList(List<Integer> defenceHeros)
    {
        this.defenceHeros = defenceHeros;
    }

    // battleRecord

    public List<DBArenaBattleRecord> getBattleRecordList()
    {
        return battleRecord;
    }


    public void setBattleRecordList(List<DBArenaBattleRecord> battleRecord)
    {
        this.battleRecord = battleRecord;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBArenaOnePlayer> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBArenaOnePlayer> SCHEMA = new Schema<DBArenaOnePlayer>()
    {
        // schema methods

        public DBArenaOnePlayer newMessage()
        {
            return new DBArenaOnePlayer();
        }

        public Class<DBArenaOnePlayer> typeClass()
        {
            return DBArenaOnePlayer.class;
        }

        public String messageName()
        {
            return DBArenaOnePlayer.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBArenaOnePlayer.class.getName();
        }

        public boolean isInitialized(DBArenaOnePlayer message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBArenaOnePlayer message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.defenceHeros == null)
                            message.defenceHeros = new ArrayList<Integer>();
                        message.defenceHeros.add(input.readInt32());break;
                    case 2:
                        if(message.battleRecord == null)
                            message.battleRecord = new ArrayList<DBArenaBattleRecord>();
                        message.battleRecord.add(input.mergeObject(null, DBArenaBattleRecord.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBArenaOnePlayer message) throws IOException
        {
            if(message.defenceHeros != null)
            {
                for(Integer defenceHeros : message.defenceHeros)
                {
                    if(defenceHeros != null)
                        output.writeInt32(1, defenceHeros, true);
                }
            }

            if(message.battleRecord != null)
            {
                for(DBArenaBattleRecord battleRecord : message.battleRecord)
                {
                    if(battleRecord != null)
                        output.writeObject(2, battleRecord, DBArenaBattleRecord.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "defenceHeros";
                case 2: return "battleRecord";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("defenceHeros", 1);
            fieldMap.put("battleRecord", 2);
        }
    };
    
}
