// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.battle.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class DBChapterRecord implements Externalizable, Message<DBChapterRecord>
{

    public static Schema<DBChapterRecord> getSchema()
    {
        return SCHEMA;
    }

    public static DBChapterRecord getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBChapterRecord DEFAULT_INSTANCE = new DBChapterRecord();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer chapterId;
    List<DBStageRecord> stageList;
    List<Boolean> boxAward;
    Integer limitStartTime;
    Integer limitFinishTime;
    Boolean limitRewardGet;

    public DBChapterRecord()
    {

    }

    public DBChapterRecord(
        Integer chapterId,
        Integer limitStartTime,
        Integer limitFinishTime,
        Boolean limitRewardGet
    )
    {
        this.chapterId = chapterId;
        this.limitStartTime = limitStartTime;
        this.limitFinishTime = limitFinishTime;
        this.limitRewardGet = limitRewardGet;
    }

    // getters and setters

    // chapterId

    public Integer getChapterId()
    {
        return chapterId;
    }


    public void setChapterId(Integer chapterId)
    {
        this.chapterId = chapterId;
    }

    // stageList

    public List<DBStageRecord> getStageListList()
    {
        return stageList;
    }


    public void setStageListList(List<DBStageRecord> stageList)
    {
        this.stageList = stageList;
    }

    // boxAward

    public List<Boolean> getBoxAwardList()
    {
        return boxAward;
    }


    public void setBoxAwardList(List<Boolean> boxAward)
    {
        this.boxAward = boxAward;
    }

    // limitStartTime

    public Integer getLimitStartTime()
    {
        return limitStartTime;
    }


    public void setLimitStartTime(Integer limitStartTime)
    {
        this.limitStartTime = limitStartTime;
    }

    // limitFinishTime

    public Integer getLimitFinishTime()
    {
        return limitFinishTime;
    }


    public void setLimitFinishTime(Integer limitFinishTime)
    {
        this.limitFinishTime = limitFinishTime;
    }

    // limitRewardGet

    public Boolean getLimitRewardGet()
    {
        return limitRewardGet;
    }


    public void setLimitRewardGet(Boolean limitRewardGet)
    {
        this.limitRewardGet = limitRewardGet;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBChapterRecord> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBChapterRecord> SCHEMA = new Schema<DBChapterRecord>()
    {
        // schema methods

        public DBChapterRecord newMessage()
        {
            return new DBChapterRecord();
        }

        public Class<DBChapterRecord> typeClass()
        {
            return DBChapterRecord.class;
        }

        public String messageName()
        {
            return DBChapterRecord.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBChapterRecord.class.getName();
        }

        public boolean isInitialized(DBChapterRecord message)
        {
            return 
                message.chapterId != null 
                && message.limitStartTime != null 
                && message.limitFinishTime != null 
                && message.limitRewardGet != null;
        }

        public void mergeFrom(Input input, DBChapterRecord message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.chapterId = input.readInt32();
                        break;
                    case 2:
                        if(message.stageList == null)
                            message.stageList = new ArrayList<DBStageRecord>();
                        message.stageList.add(input.mergeObject(null, DBStageRecord.getSchema()));
                        break;

                    case 3:
                        if(message.boxAward == null)
                            message.boxAward = new ArrayList<Boolean>();
                        message.boxAward.add(input.readBool());break;
                    case 4:
                        message.limitStartTime = input.readInt32();
                        break;
                    case 5:
                        message.limitFinishTime = input.readInt32();
                        break;
                    case 6:
                        message.limitRewardGet = input.readBool();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBChapterRecord message) throws IOException
        {
            if(message.chapterId == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.chapterId, false);

            if(message.stageList != null)
            {
                for(DBStageRecord stageList : message.stageList)
                {
                    if(stageList != null)
                        output.writeObject(2, stageList, DBStageRecord.getSchema(), true);
                }
            }


            if(message.boxAward != null)
            {
                for(Boolean boxAward : message.boxAward)
                {
                    if(boxAward != null)
                        output.writeBool(3, boxAward, true);
                }
            }

            if(message.limitStartTime == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(4, message.limitStartTime, false);

            if(message.limitFinishTime == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(5, message.limitFinishTime, false);

            if(message.limitRewardGet == null)
                throw new UninitializedMessageException(message);
            output.writeBool(6, message.limitRewardGet, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "chapterId";
                case 2: return "stageList";
                case 3: return "boxAward";
                case 4: return "limitStartTime";
                case 5: return "limitFinishTime";
                case 6: return "limitRewardGet";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("chapterId", 1);
            fieldMap.put("stageList", 2);
            fieldMap.put("boxAward", 3);
            fieldMap.put("limitStartTime", 4);
            fieldMap.put("limitFinishTime", 5);
            fieldMap.put("limitRewardGet", 6);
        }
    };
    
}
