// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.battle.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class DBCraftRecordHero implements Externalizable, Message<DBCraftRecordHero>
{

    public static Schema<DBCraftRecordHero> getSchema()
    {
        return SCHEMA;
    }

    public static DBCraftRecordHero getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBCraftRecordHero DEFAULT_INSTANCE = new DBCraftRecordHero();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer heroTplId;
    Integer starCount;

    public DBCraftRecordHero()
    {

    }

    public DBCraftRecordHero(
        Integer heroTplId,
        Integer starCount
    )
    {
        this.heroTplId = heroTplId;
        this.starCount = starCount;
    }

    // getters and setters

    // heroTplId

    public Integer getHeroTplId()
    {
        return heroTplId;
    }


    public void setHeroTplId(Integer heroTplId)
    {
        this.heroTplId = heroTplId;
    }

    // starCount

    public Integer getStarCount()
    {
        return starCount;
    }


    public void setStarCount(Integer starCount)
    {
        this.starCount = starCount;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBCraftRecordHero> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBCraftRecordHero> SCHEMA = new Schema<DBCraftRecordHero>()
    {
        // schema methods

        public DBCraftRecordHero newMessage()
        {
            return new DBCraftRecordHero();
        }

        public Class<DBCraftRecordHero> typeClass()
        {
            return DBCraftRecordHero.class;
        }

        public String messageName()
        {
            return DBCraftRecordHero.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBCraftRecordHero.class.getName();
        }

        public boolean isInitialized(DBCraftRecordHero message)
        {
            return 
                message.heroTplId != null 
                && message.starCount != null;
        }

        public void mergeFrom(Input input, DBCraftRecordHero message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.heroTplId = input.readInt32();
                        break;
                    case 2:
                        message.starCount = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBCraftRecordHero message) throws IOException
        {
            if(message.heroTplId == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.heroTplId, false);

            if(message.starCount == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.starCount, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "heroTplId";
                case 2: return "starCount";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("heroTplId", 1);
            fieldMap.put("starCount", 2);
        }
    };
    
}
