// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.battle.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBCraftRecord implements Externalizable, Message<DBCraftRecord>
{

    public static Schema<DBCraftRecord> getSchema()
    {
        return SCHEMA;
    }

    public static DBCraftRecord getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBCraftRecord DEFAULT_INSTANCE = new DBCraftRecord();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<DBCraftRecordItem> recordItem;

    public DBCraftRecord()
    {

    }

    // getters and setters

    // recordItem

    public List<DBCraftRecordItem> getRecordItemList()
    {
        return recordItem;
    }


    public void setRecordItemList(List<DBCraftRecordItem> recordItem)
    {
        this.recordItem = recordItem;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBCraftRecord> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBCraftRecord> SCHEMA = new Schema<DBCraftRecord>()
    {
        // schema methods

        public DBCraftRecord newMessage()
        {
            return new DBCraftRecord();
        }

        public Class<DBCraftRecord> typeClass()
        {
            return DBCraftRecord.class;
        }

        public String messageName()
        {
            return DBCraftRecord.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBCraftRecord.class.getName();
        }

        public boolean isInitialized(DBCraftRecord message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBCraftRecord message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.recordItem == null)
                            message.recordItem = new ArrayList<DBCraftRecordItem>();
                        message.recordItem.add(input.mergeObject(null, DBCraftRecordItem.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBCraftRecord message) throws IOException
        {
            if(message.recordItem != null)
            {
                for(DBCraftRecordItem recordItem : message.recordItem)
                {
                    if(recordItem != null)
                        output.writeObject(1, recordItem, DBCraftRecordItem.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "recordItem";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("recordItem", 1);
        }
    };
    
}
