// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.battle.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBPlayerStageRecordOld implements Externalizable, Message<DBPlayerStageRecordOld>
{

    public static Schema<DBPlayerStageRecordOld> getSchema()
    {
        return SCHEMA;
    }

    public static DBPlayerStageRecordOld getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBPlayerStageRecordOld DEFAULT_INSTANCE = new DBPlayerStageRecordOld();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<DBChapterRecordOld> chapterList;

    public DBPlayerStageRecordOld()
    {

    }

    // getters and setters

    // chapterList

    public List<DBChapterRecordOld> getChapterListList()
    {
        return chapterList;
    }


    public void setChapterListList(List<DBChapterRecordOld> chapterList)
    {
        this.chapterList = chapterList;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBPlayerStageRecordOld> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBPlayerStageRecordOld> SCHEMA = new Schema<DBPlayerStageRecordOld>()
    {
        // schema methods

        public DBPlayerStageRecordOld newMessage()
        {
            return new DBPlayerStageRecordOld();
        }

        public Class<DBPlayerStageRecordOld> typeClass()
        {
            return DBPlayerStageRecordOld.class;
        }

        public String messageName()
        {
            return DBPlayerStageRecordOld.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBPlayerStageRecordOld.class.getName();
        }

        public boolean isInitialized(DBPlayerStageRecordOld message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBPlayerStageRecordOld message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.chapterList == null)
                            message.chapterList = new ArrayList<DBChapterRecordOld>();
                        message.chapterList.add(input.mergeObject(null, DBChapterRecordOld.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBPlayerStageRecordOld message) throws IOException
        {
            if(message.chapterList != null)
            {
                for(DBChapterRecordOld chapterList : message.chapterList)
                {
                    if(chapterList != null)
                        output.writeObject(1, chapterList, DBChapterRecordOld.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "chapterList";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("chapterList", 1);
        }
    };
    
}
