// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.battle.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;


public final class DBPlayerStageRecord implements Externalizable, Message<DBPlayerStageRecord>
{

    public static Schema<DBPlayerStageRecord> getSchema()
    {
        return SCHEMA;
    }

    public static DBPlayerStageRecord getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBPlayerStageRecord DEFAULT_INSTANCE = new DBPlayerStageRecord();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    List<DBChapterRecord> chapterList;

    public DBPlayerStageRecord()
    {

    }

    // getters and setters

    // chapterList

    public List<DBChapterRecord> getChapterListList()
    {
        return chapterList;
    }


    public void setChapterListList(List<DBChapterRecord> chapterList)
    {
        this.chapterList = chapterList;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBPlayerStageRecord> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBPlayerStageRecord> SCHEMA = new Schema<DBPlayerStageRecord>()
    {
        // schema methods

        public DBPlayerStageRecord newMessage()
        {
            return new DBPlayerStageRecord();
        }

        public Class<DBPlayerStageRecord> typeClass()
        {
            return DBPlayerStageRecord.class;
        }

        public String messageName()
        {
            return DBPlayerStageRecord.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBPlayerStageRecord.class.getName();
        }

        public boolean isInitialized(DBPlayerStageRecord message)
        {
            return true;
        }

        public void mergeFrom(Input input, DBPlayerStageRecord message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        if(message.chapterList == null)
                            message.chapterList = new ArrayList<DBChapterRecord>();
                        message.chapterList.add(input.mergeObject(null, DBChapterRecord.getSchema()));
                        break;

                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBPlayerStageRecord message) throws IOException
        {
            if(message.chapterList != null)
            {
                for(DBChapterRecord chapterList : message.chapterList)
                {
                    if(chapterList != null)
                        output.writeObject(1, chapterList, DBChapterRecord.getSchema(), true);
                }
            }

        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "chapterList";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("chapterList", 1);
        }
    };
    
}
