// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protostuff

package game.module.battle.bean;


import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.GraphIOUtil;
import io.protostuff.Input;
import io.protostuff.Message;
import io.protostuff.Output;
import io.protostuff.Schema;

import io.protostuff.UninitializedMessageException;
public final class DBStageFragmentAward implements Externalizable, Message<DBStageFragmentAward>
{

    public static Schema<DBStageFragmentAward> getSchema()
    {
        return SCHEMA;
    }

    public static DBStageFragmentAward getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final DBStageFragmentAward DEFAULT_INSTANCE = new DBStageFragmentAward();

    
    // non-private fields
    // see http://developer.android.com/guide/practices/design/performance.html#package_inner
    Integer currentIndex;
    Integer awardIndex;

    public DBStageFragmentAward()
    {

    }

    public DBStageFragmentAward(
        Integer currentIndex,
        Integer awardIndex
    )
    {
        this.currentIndex = currentIndex;
        this.awardIndex = awardIndex;
    }

    // getters and setters

    // currentIndex

    public Integer getCurrentIndex()
    {
        return currentIndex;
    }


    public void setCurrentIndex(Integer currentIndex)
    {
        this.currentIndex = currentIndex;
    }

    // awardIndex

    public Integer getAwardIndex()
    {
        return awardIndex;
    }


    public void setAwardIndex(Integer awardIndex)
    {
        this.awardIndex = awardIndex;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
    }

    // message method

    public Schema<DBStageFragmentAward> cachedSchema()
    {
        return SCHEMA;
    }

    static final Schema<DBStageFragmentAward> SCHEMA = new Schema<DBStageFragmentAward>()
    {
        // schema methods

        public DBStageFragmentAward newMessage()
        {
            return new DBStageFragmentAward();
        }

        public Class<DBStageFragmentAward> typeClass()
        {
            return DBStageFragmentAward.class;
        }

        public String messageName()
        {
            return DBStageFragmentAward.class.getSimpleName();
        }

        public String messageFullName()
        {
            return DBStageFragmentAward.class.getName();
        }

        public boolean isInitialized(DBStageFragmentAward message)
        {
            return 
                message.currentIndex != null 
                && message.awardIndex != null;
        }

        public void mergeFrom(Input input, DBStageFragmentAward message) throws IOException
        {
            for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
            {
                switch(number)
                {
                    case 0:
                        return;
                    case 1:
                        message.currentIndex = input.readInt32();
                        break;
                    case 2:
                        message.awardIndex = input.readInt32();
                        break;
                    default:
                        input.handleUnknownField(number, this);
                }   
            }
        }


        public void writeTo(Output output, DBStageFragmentAward message) throws IOException
        {
            if(message.currentIndex == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(1, message.currentIndex, false);

            if(message.awardIndex == null)
                throw new UninitializedMessageException(message);
            output.writeInt32(2, message.awardIndex, false);
        }

        public String getFieldName(int number)
        {
            switch(number)
            {
                case 1: return "currentIndex";
                case 2: return "awardIndex";
                default: return null;
            }
        }

        public int getFieldNumber(String name)
        {
            final Integer number = fieldMap.get(name);
            return number == null ? 0 : number.intValue();
        }

        final java.util.HashMap<String,Integer> fieldMap = new java.util.HashMap<String,Integer>();
        {
            fieldMap.put("currentIndex", 1);
            fieldMap.put("awardIndex", 2);
        }
    };
    
}
